version: '3'

services: 
  phpapp:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: trying:123
    ports: 
      - "9040:80"
    volumes: 
      - "./:/var/www/html"
    container_name: trying_again

  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: my!!root!!!pw
    container_name: trying-db
