version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mphp-db
    environment: 
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: somedatabase
    volumes:
      - ./data:/var/lib/mysql

  dbclient:
    image: mysql:latest
    depends_on:
      - db
    command: mysql -uroot -psomepassword -hdb
    